### ISSUE TITLE
Deployed link is broken

### ISSUE THREAD

**Issue by naszifnaaz** [anshul-010/quixotic-snail-9802#11]
The submitted deployed link is broken. Deploy the app again and connect with me afterwards for project feedback and improvement

**Comment by anshul-010** [comment]
I redeployed the app, and now the link is working fine

**Comment by anshul-010** [comment]
> The submitted deployed link is broken. Deploy the app again and connect with me afterward for project feedback and improvement
I redeployed the app, and now the link is working fine

https://roaring-axolotl-876ede.netlify.app/
